sudo apt-cache search ttf-mscorefonts-installer
sudo apt-get install ttf-mscorefonts-installer
sudo apt-get install ttf-liberation
sudo apt-get install fonts-liberation
sudo apt-get install fonts-uralic
sudo apt-get install ttf-root-installer
sudo apt-get install ttf-freefont
sudo apt-get install fonts-linuxlibertine
sudo apt-get install fonts-dustin
sudo apt-get install ttf-staypuft
sudo apt-get install fonts-materialdesignicons-webfont                              
sudo apt-get install fontconfig  
sudo apt-get install fonts-mathematica
sudo apt-get install fontconfig-config
sudo apt-get install fonts-mathjax  
sudo apt-get install fonts-mikachan    
sudo apt-get install fonts-misaki
sudo apt-get install font-hosny-amiri  
sudo apt-get install fonts-mlym
sudo apt-get install font-manager       
sudo apt-get install fonts-mmcedar
sudo apt-get install fonts-moe-standard-song
sudo apt-get install fonts-adf-accanthis     
sudo apt-get install fonts-mona    
sudo apt-get install fonts-monapo                  
sudo apt-get install fonts-monlam                 
sudo apt-get install fonts-nafees                   
sudo apt-get install fonts-nakula
sudo apt-get install fonts-adf-switzera                             
sudo apt-get install fonts-alee                         
sudo apt-get install fonts-ancient-scripts                                             
sudo apt-get install fonts-oflb-asana-math
sudo apt-get install fonts-arphic-ukai                   
sudo apt-get install fonts-arphic-uming                  
sudo apt-get install fonts-oldstandard                   
sudo apt-get install fonts-opendin   
sudo apt-get install  fonts-open-sans       
sudo apt-get install fonts-opensymbol                 
sudo apt-get install fonts-oxygen                            
sudo apt-get install fonts-powerline           
sudo apt-get install fonts-circos-symbols                                          
sudo apt-get install fonts-sahadeva
sudo apt-get install fonts-croscore                     
sudo apt-get install fonts-samyak-mlym                  
sudo apt-get install fonts-samyak-orya          
sudo apt-get install fonts-samyak-taml
sudo apt-get install fonts-guru                          
sudo apt-get install fonts-hack-web                      
sudo apt-get install fonts-hanazono                      
sudo apt-get install fonts-thai-tlwg
sudo apt-get install fonts-hosny-amiri                  
sudo apt-get install fonts-tibetan-machine
sudo apt-get install fonts-indic                         
sudo apt-get install fonts-tlwg-garuda           
sudo apt-get install fonts-tlwg-kinnari
sudo apt-get install fonts-kiloji 
sudo apt-get install fonts-konatu                                   
sudo apt-get install fonttools
sudo apt-get install fonts-maitreya                     
sudo apt-get install fontypython
sudo fc-cache -fv
sudo fc-list
sudo dpkg-reconfigure fontconfig-config
reboot
