sudo apt-cache search ttf-mscorefonts-installer
sudo apt-get install ttf-mscorefonts-installer
sudo apt-get install ttf-liberation
sudo apt-get install fonts-liberation
sudo apt-get install fonts-uralic
sudo apt-get install ttf-root-installer
apt-get install ttf-freefont
sudo apt-get install fonts-linuxlibertine
sudo apt-get install fonts-dustin
sudo apt-get install ttf-staypuft
sudo apt-get install fonts-materialdesignicons-webfont                              
sudo apt-get install fontconfig  
sudo apt-get install fonts-mathematica
sudo apt-get install fontconfig-config
sudo apt-get install fonts-mathjax  
sudo apt-get install fonts-mikachan    
sudo apt-get install fonts-misaki
sudo apt-get install font-hosny-amiri  
sudo apt-get install fonts-mlym
sudo apt-get install font-manager       
sudo apt-get install fonts-mmcedar
sudo apt-get install fonts-moe-standard-kai
sudo apt-get install fonts-3270  
sudo apt-get install fonts-moe-standard-song
sudo apt-get install fonts-adf-accanthis     
sudo apt-get install fonts-mona    
sudo apt-get install fonts-monapo
sudo apt-get install fonts-adf-berenis                  
sudo apt-get install fonts-monlam
sudo apt-get install fonts-adf-oldania                  
sudo apt-get install fonts-nafees
sudo apt-get install fonts-adf-romande                   
sudo apt-get install fonts-nakula
sudo apt-get install fonts-adf-switzera                  
sudo apt-get install fonts-nanum                
sudo apt-get install fonts-adf-universalis               
sudo apt-get install fonts-alee                         
sudo apt-get install fonts-navilu
sudo apt-get install fonts-ancient-scripts              
sudo apt-get install fonts-ocr-a
sudo apt-get install fonts-arphic-bsmi00lp                                 
sudo apt-get install fonts-oflb-asana-math
sudo apt-get install fonts-arphic-ukai                   
sudo apt-get install fonts-arphic-uming                  
sudo apt-get install fonts-oldstandard
sudo apt-get install fonts-atarismall                    
sudo apt-get install fonts-opendin   
sudo apt-get install  fonts-open-sans
sudo apt-get install fonts-averia-serif-gwf            
sudo apt-get install fonts-opensymbol                 
sudo apt-get install fonts-oxygen
sudo apt-get install fonts-beng                         
sudo apt-get install fonts-pagul
sudo apt-get install fonts-blankenburg                               
sudo apt-get install fonts-powerline           
sudo apt-get install fonts-circos-symbols                        
sudo apt-get install fonts-rufscript
sudo apt-get install fonts-comfortaa                    
sudo apt-get install fonts-sahadeva
sudo apt-get install fonts-croscore                     
sudo apt-get install fonts-sambhota-tsugring                 
sudo apt-get install fonts-samyak-deva                   
sudo apt-get install fonts-samyak-mlym                  
sudo apt-get install fonts-samyak-orya          
sudo apt-get install fonts-samyak-taml
sudo apt-get install fonts-dejavu                        
sudo apt-get install fonts-sil-andika                                 
sudo apt-get install fonts-dkg-handwriting         
sudo apt-get install fonts-sil-annapurna
sudo apt-get install fonts-droid-fallback
sudo apt-get install fonts-dzongkha   
sudo apt-get install fonts-sil-scheherazade
sudo apt-get install fonts-font-awesome         
sudo apt-get install fonts-sil-sophia-nubian
sudo apt-get install fonts-smc-keraleeyam
sudo apt-get install fonts-smc-manjari
sudo apt-get install fonts-gfs-gazis          
sudo apt-get install fonts-smc-rachana
sudo apt-get install fonts-gfs-neohellenic 
sudo apt-get install fonts-gfs-theokritos                
sudo apt-get install fonts-symbola
sudo apt-get install fonts-go 
sudo apt-get install fonts-gujr                         
sudo apt-get install fonts-taml
sudo apt-get install fonts-taml-tamu
sudo apt-get install fonts-guru                          
sudo apt-get install fonts-taml-tscu
sudo apt-get install fonts-guru-extra                    
sudo apt-get install fonts-telu
sudo apt-get install fonts-hack-otf                      
sudo apt-get install fonts-telu-extra
sudo apt-get install fonts-hack-ttf                     
sudo apt-get install fonts-teluguvijayam
sudo apt-get install fonts-hack-web                      
sudo apt-get install fonts-hanazono                      
sudo apt-get install fonts-thai-tlwg
sudo apt-get install fonts-hosny-amiri                  
sudo apt-get install fonts-thai-tlwg-ttf
sudo apt-get install fonts-tibetan-machine
sudo apt-get install fonts-indic                         
sudo apt-get install fonts-tlwg-garuda
sudo apt-get install fonts-ipaexfont-mincho              
sudo apt-get install fonts-tlwg-kinnari
sudo apt-get install fonts-ipafont-mincho                
sudo apt-get install fonts-tlwg-laksaman
sudo apt-get install fonts-isabella                      
sudo apt-get install fonts-tlwg-loma-otf            
sudo apt-get install fonts-tlwg-mono
sudo apt-get install fonts-junicode                      
sudo apt-get install fonts-tlwg-mono-ttf
sudo apt-get install fonts-jura                         
sudo apt-get install fonts-kacst                      
sudo apt-get install fonts-tlwg-norasi-ttf 
sudo apt-get install fonts-kiloji 
sudo apt-get install fonts-konatu
sudo apt-get install fonts-lexi-gulim         
sudo apt-get install fonts-lindenhill                    
sudo apt-get install fonts-unfonts-core                    
sudo apt-get install fonts-unfonts-extra
sudo apt-get install fonts-vlgothic
sudo apt-get install fonts-lobster                       
sudo apt-get install fonts-vollkorn
sudo apt-get install fonts-lobstertwo                   
sudo apt-get install fonts-lohit-beng-assamese           
sudo apt-get install fonts-woowa-hanna
sudo apt-get install fonts-lohit-beng-bengali            
sudo apt-get install fonts-wqy-microhei
sudo apt-get install fonts-lohit-deva                          
sudo apt-get install fonts-yanone-kaffeesatz
sudo apt-get install fonts-yozvox-yozfont
sudo apt-get install fonts-lohit-knda                   
sudo apt-get install fonts-yozvox-yozfont-antique                
sudo apt-get install fonts-yozvox-yozfont-edu                 
sudo apt-get install fonts-lohit-taml-classical          
sudo apt-get install fonts-lohit-telu                                          
sudo apt-get install fonttools
sudo apt-get install fonts-maitreya                     
sudo apt-get install fontypython
sudo apt-get install fonts-manchufont          
sudo apt-get install fonty-rg
sudo fc-cache -fv
sudo fc-list
sudo dpkg-reconfigure fontconfig-config
reboot
