sudo apt-cache search ttf-mscorefonts-installer
sudo apt-get install ttf-mscorefonts-installer  -y
sudo apt-get install ttf-liberation -y
sudo apt-get install fonts-liberation -y
sudo apt-get install fonts-uralic -y
sudo apt-get install ttf-root-installer -y
sudo apt-get install ttf-freefont -y
sudo apt-get install fonts-linuxlibertine -y
sudo apt-get install fonts-dustin -y
sudo apt-get install ttf-staypuft -y
sudo apt-get install fonts-materialdesignicons-webfont   -y                           
sudo apt-get install fontconfig  -y
sudo apt-get install fonts-mathematica -y
sudo apt-get install fontconfig-config -y
sudo apt-get install fonts-mathjax  -y
sudo apt-get install fonts-mikachan    -y
sudo apt-get install fonts-misaki
sudo apt-get install font-hosny-amiri  -y
sudo apt-get install fonts-mlym -y
sudo apt-get install font-manager       -y
sudo apt-get install fonts-mmcedar -y
sudo apt-get install fonts-moe-standard-song  -y
sudo apt-get install fonts-adf-accanthis  -y   
sudo apt-get install fonts-mona    -y
sudo apt-get install fonts-monapo                -y  
sudo apt-get install fonts-monlam              -y   
sudo apt-get install fonts-nafees            -y       
sudo apt-get install fonts-nakula          -y
sudo apt-get install fonts-adf-switzera          -y                   
sudo apt-get install fonts-alee                -y         
sudo apt-get install fonts-ancient-scripts   -y                                          
sudo apt-get install fonts-oflb-asana-math -y
sudo apt-get install fonts-arphic-ukai     -y              
sudo apt-get install fonts-arphic-uming  -y                
sudo apt-get install fonts-oldstandard -y                  
sudo apt-get install fonts-opendin   -y
sudo apt-get install  fonts-open-sans       -y
sudo apt-get install fonts-opensymbol           -y      
sudo apt-get install fonts-oxygen             -y               
sudo apt-get install fonts-powerline        -y   
sudo apt-get install fonts-circos-symbols -y                                          
sudo apt-get install fonts-sahadeva    -y
sudo apt-get install fonts-croscore          -y           
sudo apt-get install fonts-samyak-mlym     -y             
sudo apt-get install fonts-samyak-orya   -y       
sudo apt-get install fonts-samyak-taml -y
sudo apt-get install fonts-guru             -y             
sudo apt-get install fonts-hack-web       -y               
sudo apt-get install fonts-hanazono     -y                 
sudo apt-get install fonts-thai-tlwg  -y
sudo apt-get install fonts-hosny-amiri       -y           
sudo apt-get install fonts-tibetan-machine -y
sudo apt-get install fonts-indic            -y             
sudo apt-get install fonts-tlwg-garuda    -y       
sudo apt-get install fonts-tlwg-kinnari -y
sudo apt-get install fonts-kiloji -y
sudo apt-get install fonts-konatu   -y                                
sudo apt-get install fonttools    -y
sudo apt-get install fonts-maitreya   -y                  
sudo apt-get install fontypython -y
sudo fc-cache -fv
sudo fc-list
sudo dpkg-reconfigure fontconfig-config
